import Head from "next/head";
import { Inter } from "next/font/google";
import Nav from "./components/common/Nav";
import { useState } from "react";
import Hero from "./components/home/Hero";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Koffee store</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-fit w-screen relative">
        <div className="mx-auto">
          <div className="mx-5 flex flex-col space-y-5">
            <Nav />
            <div className="bg-gray-100 rounded-xl min-h-[200px] h-fit flex justify-center items-center">
              <div className="p-5 space-y-5">
                <div className="text-4xl font-semibold">
                  Find Your Trailblazing Style With Our New Collection
                </div>
                <p className="text-gray-500">
                  Shop Our Latest Collection And Discover The Perfect Blend Of
                  Comfort And Performance For Your Hiking Needs. Find Your New
                  Must-Have Apparels Of The Season.
                </p>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
